version: '3'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    env_file:
      - .env
    ports:
      - 3306:3306
  app:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db
    env_file:
      - .env
    image: sample-web-api-go
